### ISSUE TITLE
plugin not visible for me

### ISSUE THREAD

**Issue by eregnier** [Bemjo/OBS-RTX-SuperResolution#4]
Hello,

Thank you for such a project. it looks interesting.

However, I do not see the plugin in the video filter page after setup the plugin properly (add file to obs folder)

I tested to uninstall obs 30.x to revert to 29.1.2 as you described in your readme, but I can't figure out what is missing in my setup

I run this under windows, I have nvidia video rtx installed and working with the special vlc version.

any idea how to fix this, or get insight about what's wrong ?

![image](https://github.com/Bemjo/OBS-RTX-SuperResolution/assets/5399780/e7eab6a5-b5d7-4bd0-b895-28ff3ff0180b)

![image](https://github.com/Bemjo/OBS-RTX-SuperResolution/assets/5399780/24fb010a-a7a6-4725-91ce-f1962f243a5c)

![image](https://github.com/Bemjo/OBS-RTX-SuperResolution/assets/5399780/717fcd34-a39d-4017-a477-e77fba5d7d74)

![image](https://github.com/Bemjo/OBS-RTX-SuperResolution/assets/5399780/f18dc17e-1352-4f58-9b93-892abc0bfe51)

**Comment by Bemjo** [comment]
Closing this as this seems to be a case of installation error on the users part, and there has been no response.

**Comment by eregnier** [comment]
Yes it is. Sorry fir no response and thank you for the support 🙂
