### ISSUE TITLE
Filter doesn't show up in OBS

### ISSUE THREAD

**Issue by Progamertoat** [Bemjo/OBS-RTX-SuperResolution#6]
![image](https://github.com/user-attachments/assets/4ce29536-ad6e-4889-b307-d50e137526cf)
I've installed everything and I have a RTX 3060ti.  I copied the files to OBS replaced existing ones. I restarted my computer and behold.. nothing.

**Comment by Bemjo** [comment]
@Progamertoat If you replaced existing files, was this installed previously, and did it work then?

Please check your OBS logs for any entries with rtx-superresolution or NVIDIA VIDEO FX SUPERRES, and post the relevant lines. or please provide a link to your OBS logs.

**Comment by Progamertoat** [comment]
Nevermind I had an old instalation of obs on another drive where i had accidentally pit the files. All fixed nowAm 25.08.2024 19:50 schrieb Ben Jolley ***@***.***>:
@Progamertoat If you replaced existing files, was this installed previously, and did it work then?
Please check your OBS logs for any entries with rtx-superresolution or NVIDIA VIDEO FX SUPERRES, and post the relevant lines. or please provide a link to your OBS logs.
