### ISSUE TITLE
Cant find it in plugin

### ISSUE THREAD

**Issue by Muneeb2002** [Bemjo/OBS-RTX-SuperResolution#7]
i have both folders here
![image](https://github.com/user-attachments/assets/6225adbb-d437-4a1d-b3a7-0bff211a2724)

obs isnt in a subfolder obs-studio/obs-studio
![image](https://github.com/user-attachments/assets/b65d8629-5219-4be3-acde-a56191f0a084)

i have the The nVidia Video Effects SDK
![image](https://github.com/user-attachments/assets/b4d38e4d-5948-4bee-abe9-ad226f434baa)

thank youu

**Comment by Bemjo** [comment]
Find your obs-studio installation, by default it's at C:\Program Files\obs-studio
Please extract the zip file contents from the release download into C:\Program Files, (if that is your installation path), merging with your existing obs-studio folder.

**Comment by Muneeb2002** [comment]
so i have obs in C:\Program Files\obs-studio
Does the RTX super folder need to be extracted into program files, so the files are just there or in the folder as shown above?

**Comment by Bemjo** [comment]
> so i have obs in C:\Program Files\obs-studio Does the RTX super folder need to be extracted into program files, so the files are just there or in the folder as shown above?
> 

You have downloaded the wrong file. Please download the latest release.

https://github.com/Bemjo/OBS-RTX-SuperResolution/releases/latest

**Comment by Muneeb2002** [comment]
Ohhhh I must've downloaded the source code, right my bad
